# coding: utf-8

"""
    configmanager/service.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: version not set
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from configmanager.models.configmanager_get_config_request import ConfigmanagerGetConfigRequest

class TestConfigmanagerGetConfigRequest(unittest.TestCase):
    """ConfigmanagerGetConfigRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConfigmanagerGetConfigRequest:
        """Test ConfigmanagerGetConfigRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConfigmanagerGetConfigRequest`
        """
        model = ConfigmanagerGetConfigRequest()
        if include_optional:
            return ConfigmanagerGetConfigRequest(
                tenant_id = '',
                key = '',
                business_domain = ''
            )
        else:
            return ConfigmanagerGetConfigRequest(
                tenant_id = '',
                key = '',
        )
        """

    def testConfigmanagerGetConfigRequest(self):
        """Test ConfigmanagerGetConfigRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
