# coding: utf-8

"""
    Config Manager Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from configmanager.api.config_manager_api import ConfigManagerApi


class TestConfigManagerApi(unittest.TestCase):
    """ConfigManagerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConfigManagerApi()

    def tearDown(self) -> None:
        pass

    def test_config_manager_bulk_set_configs(self) -> None:
        """Test case for config_manager_bulk_set_configs

        BulkSetConfigs
        """
        pass

    def test_config_manager_get_config(self) -> None:
        """Test case for config_manager_get_config

        GetConfig
        """
        pass

    def test_config_manager_get_tenant_id_by_code(self) -> None:
        """Test case for config_manager_get_tenant_id_by_code

        """
        pass


if __name__ == '__main__':
    unittest.main()
